name: Platform CI Checks

on:
  push:
    branches: [ main, master, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/workflows-archive-*/**'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/workflows-archive-*/**'

env:
  NODE_VERSION: '18'

jobs:
  code-quality-checks:
    name: Code Quality & Linting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint || true

    - name: Check TypeScript compilation
      run: |
        if [ -f "tsconfig.json" ]; then
          npx tsc --noEmit
        fi

  server-build-test:
    name: Server Build Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install server dependencies
      run: |
        if [ -d "server" ]; then
          cd server
          npm ci
        fi

    - name: Build server
      run: |
        if [ -d "server" ]; then
          cd server
          npm run build || true
        fi

    - name: Verify enhanced server build
      run: |
        if [ -f "server/dist/standalone-enhanced-server-production.js" ]; then
          echo "✅ Enhanced server build successful"
          ls -la server/dist/standalone-enhanced-server-production.js
        else
          echo "⚠️  Enhanced server build not found (this may be expected)"
        fi

  frontend-build-test:
    name: Frontend Build Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build || true

    - name: Check build artifacts
      run: |
        if [ -d "dist" ]; then
          echo "✅ Frontend build successful"
          ls -la dist/
        else
          echo "⚠️  Frontend build directory not found"
        fi

  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --audit-level=moderate || true

    - name: Check for known vulnerabilities
      run: |
        echo "🔍 Security scan completed"
        echo "Note: This is a non-blocking check for awareness"

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [code-quality-checks, server-build-test, frontend-build-test, security-scan]
    if: always()
    
    steps:
    - name: Display summary
      run: |
        echo "🚀 Platform CI Checks Summary"
        echo "============================"
        echo "Code Quality: ${{ needs.code-quality-checks.result }}"
        echo "Server Build: ${{ needs.server-build-test.result }}"
        echo "Frontend Build: ${{ needs.frontend-build-test.result }}"
        echo "Security Scan: ${{ needs.security-scan.result }}"
        echo ""
        echo "ℹ️  Note: This workflow only runs checks and tests."
        echo "ℹ️  Deployment must be triggered manually via 'Enhanced Email API Deployment' workflow."
        echo ""
        if [[ "${{ needs.code-quality-checks.result }}" == "success" && "${{ needs.server-build-test.result }}" == "success" ]]; then
          echo "✅ All critical checks passed - ready for manual deployment"
        else
          echo "⚠️  Some checks failed - review before deploying"
        fi
